# custom MultiQC config file

# report title and metadata
report_title: "PacBio Longread Alzheimer's Disease Pilot"
intro_text: "This report contains quality metrics and analysis results from our pipeline."

# software versions
custom_content:
  software_versions:
    section_name: "Software Versions"
    description: "Versions of software tools used in this analysis"
    plot_type: "table"
    data:
      Tool: ["lima", "pbskera", "isoseq", "pbmm2", "kallisto", "bustools", "samtools", "nextflow", "multiqc"]
      Version: ["2.13.0", "1.4.0", "4.3.0", "1.17.0", "0.51.1", "0.45.1", "1.22", "25.04.3", "1.30"]

# iso-Seq refine sections
isoseq/refine-csv:
  contents: id,strand,fivelen,threelen,polyAlen,insertlen,primer
  fn: "*.csv"

isoseq/refine-json:
  contents: '"num_reads_fl"'
  fn: "*.json"

# skera
skera:
  fn: "*.json"
  section_name: "Skera Summary"
  description: "Statistics from Skera analysis (S-Reads, array metrics)"
  plot_type: "generalstats"
  pconfig:
    id: "skera_stats_table"
    title: "Skera Metrics"
    namespace: "Skera"
    decimalPlaces: 2
  headers:
    reads: {title: "Total Reads", format: "{:,.0f}", scale: "Blues"}
    s_reads: {title: "S-Reads", format: "{:,.0f}", scale: "Greens"}
    mean_len_s_reads: {title: "Mean S-Read Length", suffix: " bp", scale: "Oranges"}
    percent_full_array: {title: "Full Array %", suffix: "%", scale: "RdYlGn", max: 100, min: 0}
    mean_array_size: {title: "Mean Array Size", scale: "Purples", decimalPlaces: 2}
  data_format: "json"
  data_fields:
    - key: "attributes"
      fields:
        - id: "reads"
        - id: "s_reads"
        - id: "mean_len_s_reads"
        - id: "percent_full_array"
        - id: "mean_array_size"

# pbmm2
sp:
  pbmm2:
    fn: "pbmm2_stats.csv"
    section_name: "pbmm2 Alignment Stats"
    description: "Statistics parsed from pbmm2 alignment logs"
    format: "csv"
    headers:
      Sample: "Sample"
      Mapped_Reads: {title: "Mapped Reads", format: "{:,.0f}", scale: "Blues"}
      Mapping_Rate: {title: "Mapping Rate (%)", suffix: "%", scale: "RdYlGn", max: 100}
      Avg_Coverage: {title: "Avg Coverage (X)", suffix: "X", scale: "Purples"}

# kallisto
kallisto:
  fn: "*lrkallisto*.log"
  num_lines: 20
  pconfig:
    pseudoaligned_reads: {title: "Pseudoaligned Reads", format: "{:,.0f}"}
    pseudoalignment_rate: {title: "Pseudoalignment Rate", suffix: "%"}

# General settings
ignore_images: false
export_plots: true
no_report: false
force: true